### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by bkruger99** [scopely-devops/skew#111]
Hi,

I'm curious if this is still being worked on or being abandoned ?  If it's being abandoned, could the code be transferred to someone who is willing to work on it?   This is incredibly useful, but could be extended to be even more powerful..

Thanks!

**Comment by avram** [comment]
We aren't currently using this at Scopely, and I don't believe @garnaat is actively using it in his work, so he may also not be very on top of the PRs into the repo.

If anyone would like to take on maintenance, we're more than happy to grant access and/or transfer the repo into a new organization (i.e., skew/skew), transfer ownership and grant PyPI write access.

**Comment by garnaat** [comment]
I don't have a lot of cycles for this but I am still supportive and would like to see it extended.  As @avram says, if anyone wants the commit bit let us know.

**Comment by garnaat** [comment]
I am certainly willing to consider PR's as long as they have some tests supporting them.

**Comment by bkruger99** [comment]
@garnaat Would you be willing to spend some time vetting pull requests?  Your python skills are better than mine, but I certainly wouldn't mind helping out with them.  If it's a few minutes a week, that would be sufficient I think, I don't think they'd be coming frequently.   I have some contributions I'd like to do, but it's something I'd like to see go into a main branch for everyone rather than having the code mixed all over the place.

Things I'd like to add: 
Enumerate regions and services from botocore's json files rather than hardcoding them in here.
Command line util to run outright 
Allow accounts to be added via code (there was a pull req for it) or via the config file.
Vet and merge any of the current pull requests if they make sense.

Maybe multi-cloud support
Maybe add moto (https://github.com/spulec/moto) for testing as well in addition to placebo and some functional testing so we catch things like #110.

@avram If you'd like to add me to the repo, I can help vet requests and try to be active with it.  Or if @garnaat would like to take it back and then pull requests sent his direction, that's fine too.  If neither and scopley wants to get rid of it and @garnaat doesn't want it, then I'm happy to pick it up.   This just happens to be quite a useful utility with a lot more potential and it would be sad to see it abandoned.

-b

**Comment by garnaat** [comment]
@bkruger99 I will definitely help review PR's.

I think adding you to the repo makes sense since you are using it more actively than either @avram or I.  I have no problem with it living in the Scopely org but if it's more trouble than it's worth for them we can certainly find a new home for it.

**Comment by avram** [comment]
@bkruger99 I've added you to the "Open Source" team in this organization. Welcome to the team!

If and when it makes sense to grant access to things like the PyPI for this, we'll handle that too.
