### ISSUE TITLE
govcloud?

### ISSUE THREAD

**Issue by steveheistand** [scopely-devops/skew#112]
Hi folks, this thing is a life saver on the pubcloud side.
But not working with govcloud is a shame.
Any thoughts on adding in the govcloud region?

thanks

steve

**Comment by steveheistand** [comment]
to follow up on my own comment. it seems to work (at least well enough for my needs)
just by adding the us-gov-west-1 region into the _all_region_names declaration.

s

**Comment by garnaat** [comment]
Good.  I was just going to suggest that but I'm glad you were able to find it yourself and get unstuck.
