### ISSUE TITLE
Internet Gateway does not execute

### ISSUE THREAD

**Issue by zebanaaz** [scopely-devops/skew#129]

**Comment by zebanaaz** [comment]
It shows no output even when there are internet-gateways exists in our account.

**Comment by zebanaaz** [comment]
Created a pull request to fix this issue : https://github.com/scopely-devops/skew/pull/130

**Comment by rsimac** [comment]
Confirming the internet gateways are not scan()ned , neither the 'default' one nor any additional ones. Would be nice if above pull request is merged and pushed upstream to pip repos. Thanks for the great library.
