### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by bhyde** [scopely-devops/skew#147]
[caniusepython3](https://github.com/brettcannon/caniusepython3) reports that skew won't work for me as we move to python3, which makes me very sad.

```
bash-3.2$ caniusepython3 --requirement ../requirements.txt 
Finding and checking dependencies ...

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  skew
```

FYI, this is the requirements.txt for that example.

```
bash-3.2$ cat ../requirements.txt 
PyYAML
future
futures
arrow
boto
boto3
functools32
lazy
munch
netaddr
plumbum
pycrypto
pymongo
skew
slackclient
tabulate
troposphere
networkx
docopt
```

**Comment by garnaat** [comment]
I haven't really tried but I really don't think it would be much of an effort to get skew upgraded to be Python 3 compatible.  I'll give it a try this weekend.

**Comment by garnaat** [comment]
I tried the develop branch over the weekend and it worked just fine on Python 3.7.

Do we know why caniusepython3 is saying it does not work?

**Comment by avram** [comment]
Python3 is covered in the test matrix w/ no issue.
