### ISSUE TITLE
What kind for permissions are required for running skew?

### ISSUE THREAD

**Issue by twitu** [scopely-devops/skew#148]
I tested a skew script in `god_mode` and it worked perfectly as it should. However, it would be great to know the permissions required so I can create an IAM role for the script. Instead you could also mention the kind of operations skew performs and I can make a policy accordingly. Thank you for the help.

**Comment by avram** [comment]
Skew makes various read requests against every service you have it scanning-- it would be hard to define any narrower policy than the built-in global read policy.

**Comment by twitu** [comment]
Thanks I think that should do it. For reference I have included a link to the [ReadOnlyAccess](https://console.aws.amazon.com/iam/home?region=us-east-1#policies/arn:aws:iam::aws:policy/ReadOnlyAccess) policy.
