### ISSUE TITLE
Add multithreading

### ISSUE THREAD

**Issue by geekpete** [scopely-devops/skew#27]
Ok I'll be the first to log a ticket.

I've assumed that generally your library can be made more performant by adding multithreading.

For some calls, like grabbing a list of all autoscaling groups, a single call pulls back all the data for a single region. For this reason, to start with maybe the connections to the regions could be multithreaded with as many threads as there are regions.

This allows all the network calls to happen concurrently across regions.

Should speed things up markedly if the library doesn't already do this.

Of course, this adds complexity but it should be worth it in the speed gains.

Cheers.

**Comment by faridnsh** [comment]
Here's how I solved this problem in my script: 

```
class Worker(Thread):
   def __init__(self, arn):
       Thread.__init__(self)
       self.arn = arn
       self.name = arn

   def run(self):
       for i in skew.scan(self.arn):
           # now do something with the stuff

arn = ARN()

for service in arn.service.choices():
    uri = 'arn:aws:' + service + ':*:*:*/*
    worker = Worker(uri);
    worker.start()
```

You can make add the region and service type for loops, it'll be faster but it'll take more memory.
