### ISSUE TITLE
AccessDenied error

### ISSUE THREAD

**Issue by vapniks** [scopely-devops/skew#81]
After your latest update I no longer get the `aws_creds` error when running this script: http://bit.ly/1JJ0TH2
Thankyou. However I now get another error:

```
/usr/local/lib/python2.7/dist-packages/botocore/client.pyc in _make_api_call(self, operation_name, api_params)
    405 
    406         if http.status_code >= 300:
--> 407             raise ClientError(parsed_response, operation_name)
    408         else:
    409             return parsed_response

ClientError: An error occurred (AccessDenied) when calling the DescribeStacks operation: User: arn:aws:iam::<ID>:user/<NAME> is not authorized to perform: cloudforma
tion:DescribeStacks
```

**Comment by garnaat** [comment]
Hmm, is it possible the credentials you are using do not have permission to ``DescribeStacks``?  The support for Cloudformation is new.

**Comment by garnaat** [comment]
I guess we need a way to handle these errors more gracefully or perhaps to control which resources will be enumerated.

**Comment by vapniks** [comment]
How can I programatically check which resources I have permissions for?

**Comment by garnaat** [comment]
Can you try running ``aws cloud formation describe-stacks`` with the AWSCLI?

**Comment by vapniks** [comment]
Tried it, and got this error:
```
A client error (AccessDenied) occurred when calling the DescribeStacks operation: User: arn:aws:iam::<ID>:user/<NAME> is not authorized to perform: cloudformation:DescribeStacks
```

**Comment by rsmolkin** [comment]
I'm getting the same error, I had to add a CreateStack inline policy to get permission to Create them, but not sure how to modify that policy for Describe Stacks http://stackoverflow.com/questions/34237218/user-is-not-authorized-to-perform-cloudformationcreatestack
