### ISSUE TITLE
Scan results returning a positive result for each account

### ISSUE THREAD

**Issue by npolonski** [scopely-devops/skew#91]
In version 0.16.1 I'm running a query against 3 accounts and defining the accounts in the code using:

```
  skew.config._config = {
      'accounts': {
          'ACCT1' : {'profile': None},
          'ACCT2' : {'profile': None},
          'ACCT3' : {'profile': None},
       }
  }
```

When I run a scan for an ec2 instance id, I get back positive results from all 3 accounts even though the instance only exists in 1 account.

**Comment by garnaat** [comment]
I'm having trouble recreating this.  Prior to the fix for #90 I was getting a traceback because the instance ID was not found in two of the regions.  After the fix, I'm seeing just a single resource returned.

I'm enumerating an arn like this:

```
arn:aws:ec2:us-west-2:*:instance/i-12345678
```

Am I misunderstanding?
