### ISSUE TITLE
pypi release to fix pyyaml dep hardcode

### ISSUE THREAD

**Issue by kapilt** [scopely-devops/skew#99]
else it can cause skew installation errors when used as a dependency due to mismatched pypi versions across transitive dep set on pyyaml otherwise. ie. if one dep depends on any version greater than pyyaml > 3.11 and skew in current form pins it to 3.11 and 3.12 gets installed for the other dep, then skew install barfs. 

simple fix was already merged in #97 but needs a release to close the loop.

**Comment by kapilt** [comment]
bump.. any chance we can get a release for the dependency fix/issue on pyyaml version hardcode?

**Comment by avram** [comment]
Released https://pypi.org/project/skew/0.17.0/
